% function [fitCharacteristics]=Rel_FF_Single_Cone_Analyses(stimRootDir, controlRootDir)
% [fitCharacteristics]=Rel_FF_Single_Cone_Analyses(stimRootDir, controlRootDir)
%
%   Calculates pooled variance across a set of pre-analyzed 
%   signals from a single cone's stimulus and control trials, performs 
%   the subtraction between its standard deviations, and performs a
%   piecewise fit of the subtraction.
%
%   This script is designed to work with FULL FIELD datasets- that is, each
%   dataset (mat file) contains *only* control or stimulus data.
%
%   Normally, the user doesn't need to select a stimulus or control root
%   directory, but if the software is run by
%   itself it will prompt the user for the folders containing the
%   pre-analyzed mat files generated by Rel_FF_Temporal_Reflectivity_Analysis.m.
%
% Inputs:
%       stimRootDir: The folder path of the pre-analyzed (.mat) stimulus
%       trials. Each mat file must contain valid stimulus signals.
%
%       controlRootDir: The folder path of the pre-analyzed (.mat) control
%       trials. Each mat file must contain valid control signals.
%
%
% Outputs:
%       fitCharacteristics: Information extracted from the mat files and
%       the fitted subtracted signal.
%
% Created by Robert F Cooper 2017-10-31
%

clear;


CUTOFF = 10;
NUMTRIALS= 10;
CRITICAL_REGION = 72:90; % 72:90;
window_size = 5;
half_window = floor(window_size/2);

pipeline_type = 'stddev'; % Legacy mode is 'stddev', moving_rms is new

CELL_OF_INTEREST = [1:1000];

if isempty(CELL_OF_INTEREST)
    close all force;
end

if ~exist('stimRootDir','var')
    stimRootDir = uigetdir(pwd, 'Select the directory containing the stimulus profiles');
    controlRootDir = uigetdir(pwd, 'Select the directory containing the control profiles');
end

profileSDataNames = read_folder_contents(stimRootDir,'mat');
profileCDataNames = read_folder_contents(controlRootDir,'mat');


% For structure:
% /stuff/id/date/wavelength/time/intensity/location/data/Profile_Data

[remain kid] = getparent(stimRootDir); % data
[remain stim_loc] = getparent(remain); % location 
[remain stim_intensity] = getparent(remain); % intensity 
[remain stim_time] = getparent(remain); % time
[remain stimwave] = getparent(remain); % wavelength
% [remain sessiondate] = getparent(remain); % date
[~, id] = getparent(remain); % id
outFname = [id '_' stimwave '_' stim_intensity '_' stim_time  '_' stim_loc '_' num2str(length(profileSDataNames)) '_single_cone_signals'];


%% Code for determining variance across all signals at given timepoint

THEwaitbar = waitbar(0,'Loading stimulus profiles...');

max_index=0;

load(fullfile(stimRootDir, profileSDataNames{1}));
stim_coords = ref_coords;

if ~isempty(CELL_OF_INTEREST)
    stim_cell_reflectance = cell(length(profileSDataNames),1);
end
stim_cell_reflectance_nonorm = cell(length(profileSDataNames),1);
stim_time_indexes = cell(length(profileSDataNames),1);
stim_cell_prestim_mean = cell(length(profileSDataNames),1);

for j=1:length(profileSDataNames)

    waitbar(j/length(profileSDataNames),THEwaitbar,'Loading stimulus profiles...');
    
    ref_coords=[];
    profileSDataNames{j}
    load(fullfile(stimRootDir,profileSDataNames{j}));
    
    
    stim_cell_reflectance_nonorm{j} = cell_reflectance;
    
    stim_cell_reflectance{j} = norm_cell_reflectance;
    stim_time_indexes{j} = cell_times;
    stim_cell_prestim_mean{j} = cell_prestim_mean;
    
    thesecoords = union(stim_coords, ref_coords,'rows');
    
    % These all must be the same length! (Same coordinate set)
    if size(ref_coords,1) ~= size(thesecoords,1)
        error('Coordinate lists different between mat files in this directory. Unable to perform analysis.')
    end
    
    for k=1:length(cell_times)
        max_index = max([max_index max(cell_times{k})]);
    end
    
end

%%
if ~isempty(CELL_OF_INTEREST)
    control_cell_reflectance = cell(length(profileCDataNames),1);
end
control_cell_reflectance_nonorm = cell(length(profileCDataNames),1);
control_time_indexes = cell(length(profileCDataNames),1);
control_cell_prestim_mean = cell(length(profileCDataNames),1);

load(fullfile(controlRootDir, profileCDataNames{1}));
control_coords = ref_coords;

for j=1:length(profileCDataNames)

    waitbar(j/length(profileCDataNames),THEwaitbar,'Loading control profiles...');
    
    ref_coords=[];
    profileCDataNames{j}
    load(fullfile(controlRootDir,profileCDataNames{j}));
    
    if ~isempty(CELL_OF_INTEREST)
        control_cell_reflectance_nonorm{j} = cell_reflectance;
    end
    control_cell_reflectance{j} = norm_cell_reflectance;
    control_time_indexes{j} = cell_times;
    control_cell_prestim_mean{j} = cell_prestim_mean;

    thesecoords = union(control_coords, ref_coords,'rows');
    
    % The length of the cell reflectance lists *must* be the same, because the
    % coordinate lists *must* be the same in each mat file.
    if size(ref_coords,1) ~= size(thesecoords,1)
        error('Coordinate lists different between mat files in this directory. Unable to perform analysis.')
    end
    
    for k=1:length(cell_times)
        max_index = max([max_index max(cell_times{k})]);
    end
    
end

%% The coordinate lists must the same length,
% otherwise it's not likely they're from the same set.

if size(stim_coords,1) ~= size(control_coords,1)
    error('Coordinate lists different between control and stimulus directories. Unable to perform analysis.')
end

allcoords = stim_coords;


% Aggregation of all trials
%% Control trial aggregation

numcontrolcoords = size(control_coords,1);

control_cell_var = nan(size(control_coords,1), max_index);
control_cell_median = nan(size(control_coords,1), max_index);
control_cell_pca_std = nan(size(stim_coords,1), 1);
control_trial_count = zeros(size(control_coords,1),1);
control_posnegratio = nan(size(control_coords,1),max_index);
cont_prestim_means=[];

all_times_ref = nan(numcontrolcoords*length(profileCDataNames), max_index);
if ~isempty(CELL_OF_INTEREST)
    nonorm_ref = nan(numcontrolcoords*length(profileCDataNames), max_index);
end

for i=1:numcontrolcoords
    waitbar(i/size(control_coords,1),THEwaitbar,'Processing control signals...');

    numtrials = 0;

    for j=1:length(profileCDataNames)
                        
        if ~isempty(control_cell_reflectance{j}{i}) && ...
           sum(control_time_indexes{j}{i} >= CRITICAL_REGION(1) & control_time_indexes{j}{i} <= CRITICAL_REGION(end)) >=  CUTOFF && ...
           control_cell_prestim_mean{j}(i) <= 240
       
            cont_prestim_means = [cont_prestim_means; control_cell_prestim_mean{j}(i)];
            numtrials = numtrials+1;
            if ~isempty(CELL_OF_INTEREST)
                this_nonorm_ref(j, control_time_indexes{j}{i} ) = control_cell_reflectance_nonorm{j}{i}(~isnan(control_cell_reflectance_nonorm{j}{i}));
            end
            this_ref(j, control_time_indexes{j}{i} ) = control_cell_reflectance{j}{i};
        end
    end
    control_trial_count(i) = numtrials;

    all_times_ref( ((i-1)*length(profileCDataNames)+1):(i*length(profileCDataNames)),: ) = this_ref;

end

all_times_ref = all_times_ref(:,2:end);
all_control_ref = all_times_ref;
notnans= ~all(isnan(all_times_ref),2);

% Remove the all nan rows, drop the first never used index.
% Explains 95% of variance, selecting the first 5 components
[COEFF, SCORE, LATENT, TSQUARED, EXPLAINED, MU] = pca(all_times_ref(notnans, :),'Algorithm','als');


all_control_ref(notnans,:) = SCORE*COEFF';
return;
%% Stimulus trial aggregation
percentparula = parula(101);

numstimcoords = size(stim_coords,1);

stim_cell_var = nan(numstimcoords, max_index);
stim_cell_median = nan(numstimcoords, max_index);
stim_resp_range = nan(numstimcoords, 1);
stim_trial_count = zeros(numstimcoords,1);
stim_posnegratio = nan(numstimcoords,max_index);
stim_prestim_means = nan(numstimcoords,length(profileSDataNames));

i=1;
allstimsignals=cell(numstimcoords,1);


all_times_ref = nan(numstimcoords*length(profileSDataNames), max_index);
if ~isempty(CELL_OF_INTEREST)
    nonorm_ref = nan(numstimcoords*length(profileSDataNames), max_index);
end
for i=1:numstimcoords
    waitbar(i/size(stim_coords,1),THEwaitbar,'Processing stimulus signals...');

    this_ref = nan(length(profileSDataNames), max_index);
    if ~isempty(CELL_OF_INTEREST)
        this_nonorm_ref = nan(length(profileSDataNames), max_index);
    end
    numtrials = 0;
    
    for j=1:length(profileSDataNames)
        
        if ~isempty(stim_cell_reflectance{j}{i}) && ...
           sum(stim_time_indexes{j}{i} >= CRITICAL_REGION(1) & stim_time_indexes{j}{i} <= CRITICAL_REGION(end)) >= CUTOFF && ...
           stim_cell_prestim_mean{j}(i) <= 240

            stim_prestim_means(i,j) = stim_cell_prestim_mean{j}(i);
            numtrials = numtrials+1;
            
            this_nonorm_ref( j, stim_time_indexes{j}{i} ) = stim_cell_reflectance_nonorm{j}{i}(~isnan(stim_cell_reflectance_nonorm{j}{i}));
                
            this_ref( j, stim_time_indexes{j}{i} ) = stim_cell_reflectance{j}{i};

        end       
    end
    
    all_times_ref( ((i-1)*length(profileSDataNames)+1):(i*length(profileSDataNames)),: ) = this_ref;

end
all_times_ref = all_times_ref(:,2:end);
all_stim_ref = all_times_ref;
notnans= ~all(isnan(all_times_ref),2);

% Remove the all nan rows, drop the first never used index.
% Explains 95% of variance, selecting the first 5 components
[COEFF, SCORE, LATENT, TSQUARED, EXPLAINED, MU] = pca(all_times_ref(notnans, :),'Algorithm','als');


all_stim_ref(notnans,:) = SCORE*COEFF';

return;

%%


valid = (stim_trial_count >= NUMTRIALS) & (control_trial_count >= NUMTRIALS);

% Calculate the pooled std deviation
std_dev_sub = sqrt(stim_cell_var)-mean(sqrt(control_cell_var),'omitnan');
control_std_dev_sub = sqrt(control_cell_var)-mean(sqrt(control_cell_var),'omitnan');
median_sub = stim_cell_median-mean(control_cell_median,'omitnan');
control_median_sub = control_cell_median-mean(control_cell_median,'omitnan');


%% Analyze the signals

AmpResp = nan(size(std_dev_sub,1),1);
MedianResp = nan(size(std_dev_sub,1),1);
TTPResp = nan(size(std_dev_sub,1),1);
PrestimVal = nan(size(std_dev_sub,1),1);

ControlAmpResp = nan(size(std_dev_sub,1),1);
ControlMedianResp = nan(size(std_dev_sub,1),1);
ControlPrestimVal = nan(size(std_dev_sub,1),1);
hz=17.85;
allinds = 1:length(std_dev_sub);
for i=1:size(std_dev_sub,1)
 waitbar(i/size(std_dev_sub,1),THEwaitbar,'Analyzing subtracted signals...');

    if ~all( isnan(std_dev_sub(i,2:end)) ) && valid(i)
        
        % Stimulus with control subtracted
        std_dev_sig = std_dev_sub(i,2:end);        
        nanners = ~isnan(std_dev_sig);
        firstind=find(cumsum(nanners)>0);
        [~, lastind] = max(cumsum(nanners)-sum(nanners));
        interpinds = firstind(1):lastind;
        goodinds = allinds(nanners);
        std_dev_sig = interp1(goodinds, std_dev_sig(nanners), interpinds, 'makima');
        filt_stim_sig(i,:) = std_dev_sig;

        median_sig = median_sub(i,2:end);
        nanners = ~isnan(median_sig);
        firstind=find(cumsum(nanners)>0);
        [~, lastind] = max(cumsum(nanners)-sum(nanners));
        interpinds = firstind(1):lastind;
        goodinds = allinds(nanners);
        median_sig = interp1(goodinds, median_sig(nanners), interpinds, 'makima');
        filt_median_sig = median_sig;

        critical_filt = filt_stddev_sig( CRITICAL_REGION );
        
        [~, TTPResp(i)] = max( abs(critical_filt) );    
        AmpResp(i) = quantile(critical_filt,0.95);
        MedianResp(i) = max(abs(filt_median_sig(CRITICAL_REGION))-mean(filt_median_sig(1:CRITICAL_REGION(1))) );        
        PrestimVal(i) = mean( stim_prestim_means(i,:),2, 'omitnan');
        
        if any(i==CELL_OF_INTEREST)
           figure(1);
           subplot(2,1,1);
           plot( interpinds/hz, filt_stddev_sig ); hold on; plot(interpinds/hz,std_dev_sig);
           plot( interpinds/hz,filt_median_sig ); plot(interpinds/hz, median_sig);
%            plot(sqrt(control_cell_var(i,2:end))-1);
%            plot(sqrt(stim_cell_var(i,2:end))-1);
%            plot(mean(sqrt(control_cell_var),'omitnan'));
           title(['#: ' num2str(i) ' A: ' num2str(AmpResp(i)) ', M: ' num2str(MedianResp(i)) ', LogResp: ' num2str(log10(AmpResp(i)+MedianResp(i)+1)) ]);
           axis([0 9 -5 10]); hold off;
           
           subplot(2,1,2); 
%            plot((0:69)/hz, criticalfit(i,:));hold on;
%            plot(densitometry_vect_times{i},densitometry_vect_ref{i},'.'); hold off;           
%            title(['FitAmp: ' num2str(densitometry_fit_amplitude(i))]);axis([0 2 0 1.5]);
           drawnow; 
           
%            saveas(gcf, ['Cell_' num2str(i) '_stimulus.png']);
        end
        
        % Control only
        std_dev_sig = control_std_dev_sub(i,2:end);
        nanners = ~isnan(std_dev_sig);
        firstind=find(cumsum(nanners)>0);
        [~, lastind] = max(cumsum(nanners)-sum(nanners));
        interpinds = firstind(1):lastind;
        goodinds = allinds(nanners);
        std_dev_sig = interp1(goodinds, std_dev_sig(nanners), interpinds, 'makima');
        filt_stddev_sig = std_dev_sig;

        
        median_sig = control_median_sub(i,2:end);        
        nanners = ~isnan(median_sig);        
        firstind=find(cumsum(nanners)>0);
        [~, lastind] = max(cumsum(nanners)-sum(nanners));
        interpinds = firstind(1):lastind;
        goodinds = allinds(nanners);        
        median_sig = interp1(goodinds, median_sig(nanners), interpinds, 'makima');
        filt_median_sig = median_sig;


        critical_filt = filt_stddev_sig( CRITICAL_REGION );
        
        ControlAmpResp(i) = quantile(critical_filt,0.95);
        ControlMedianResp(i) = max(abs(filt_median_sig(CRITICAL_REGION))-mean(filt_median_sig(1:CRITICAL_REGION(1))) );        
        ControlPrestimVal(i) = mean( cont_prestim_means(i,:),2, 'omitnan');
%         histogram(filt_stddev_sig(CRITICAL_REGION),20)

    end
end
%%
close(THEwaitbar);

save([ outFname '.mat'],'pipeline_type', 'AmpResp','MedianResp','TTPResp',...
     'ControlAmpResp','ControlMedianResp','ControlPrestimVal',...
     'valid','allcoords','ref_image','control_cell_median',...
     'control_cell_var','stim_cell_median','stim_cell_var','stim_prestim_means','stim_resp_range','allstimsignals');

 

%% Plot the pos/neg ratio of the mean vs the amplitude
posnegratio=nan(size(control_coords,1),1);


figure(101); clf; hold on;
for i=1:size(control_coords,1)
    if ~isnan(AmpResp(i))
        % Find out what percentage of time the signal spends negative
        % or positive after stimulus delivery (66th frame)
%         numposneg = sign(mean_sub(i,:));
%         pos = sum(numposneg == 1);
% 
%         posnegratio(i) = 100*pos/length(numposneg);

%         if mean(stim_prestim_means(i,:),'omitnan') > 150 && mean(stim_prestim_means(i,:),'omitnan') < 152
%             disp(num2str(i));
%         end
        plot( mean(stim_prestim_means(i,:),'omitnan'),AmpResp(i)+abs(MedianResp(i)),'k.');        
    end
end
% ylabel('Median response amplitude');
% xlabel('Reflectance response amplitude');
% title('Median reflectance vs reflectance response amplitude')
hold off;
% saveas(gcf,['posneg_vs_amp_' num2str(stim_intensity) '.png']);
%% Plot histograms of the amplitudes
figure(7);
histogram( AmpResp(~isnan(AmpResp)) ,'Binwidth',0.1);
title('Stim-Control per cone subtraction amplitudes');
xlabel('Amplitude difference from control');
ylabel('Number of cones');
%%
goodtrials = ~isnan(AmpResp);

figure(8); clf; hold on;
imagesc(ref_image); colormap gray; axis image;
for i=1:length(goodtrials)
    if goodtrials(i) && AmpResp(i)<=0
        plot(allcoords(i,1), allcoords(i,2),'*');
    end
end
